### ISSUE TITLE
Request to Firebase Extensions url for Firestore Stripe Payments often fails

### ISSUE THREAD

**Issue by alexdao3** [stripe/stripe-firebase-extensions#405]
# Bug report

- Extension name: `firestore-stripe-payments`

## Describe the bug

In one of our CI (Github Actions) workflows, we start up the emulator w/ extensions & run tests against it. The extensions are defined in `firebase.json` config, one of which is 

`"firestore-stripe-subscriptions": "stripe/firestore-stripe-payments@0.2.4"`. 

During startup, the emulator appears to make a request to https://firebaseextensions.googleapis.com/v1beta/publishers/stripe/extensions/firestore-stripe-payments. Oftentimes this request fails and we get the following error:

```Error: Failed to make request to https://firebaseextensions.googleapis.com/v1beta/publishers/stripe/extensions/firestore-stripe-payments```

Occasionally we don't see this error, and the emulator successfully starts up (presumably this means that the request above succeeds). Even when re-running the same CI workflow (without any changes to anything), the request may fail on the first run but succeed on the second run (or vice versa)

So far we've only observed this inconsistent behavior in CI and have never encountered this error on local dev w/ emulators.

For the Github action workflow, I'm providing the following env variables:
```
FIREBASE_TOKEN (generated via "npx firebase login:ci")
PROJECT_ID
```

and invoking

```
npx firebase use --add "$PROJECT_ID"
npx firebase emulators:exec 'npm run test'
```

## To Reproduce

I don't currently have a minimal reproducible example due to this being in our private GH actions workflow, but let me know if this is necessary and I can try to create a minimal public version.

## Expected behavior

I expect the emulators to be able to start up or get some feedback as to why the request was unsuccessful. I also expect the behavior to be consistent between consecutive CI runs (when there are no code changes)

## Screenshots

When this fails: 
<img width="995" alt="image" src="https://user-images.githubusercontent.com/35239179/177827593-28a171ee-0294-45d6-b8bd-c0cc5447e2cf.png">

## System information

- OS: Ubuntu

**Comment by dackers86** [comment]
HI @alexdao3 

It seems like some processes are taking place before the emulator (or some other process) is starting up?

Do you have any additional debugging, or can you provide any details? It is difficult to see which of the [api](https://github.com/firebase/firebase-tools/search?p=1&q=publishers) calls could be causing the issue.

**Comment by alexdao3** [comment]
Your question about additional debugging spurred me to try running `npx firebase emulators... --debug`. I had forgotten there was a `--debug` option. Hopefully it'll yield interesting information - I'll share back if so!

**Comment by dackers86** [comment]
Could you confirm what version of the Firebase cli and node are you using?

Firebase --version

Node -v

**Comment by alexdao3** [comment]
Node `16.13.1` 
Firebase tools `11.2.2`

**Comment by alexdao3** [comment]
@dackers86 Do you have any insight into this issue?

**Comment by alexdao3** [comment]
@dackers86 Hi Darren, just wanted to follow up to see if you had any ideas on this failing request

**Comment by nickpell** [comment]
@dackers86 @jsteele-stripe Do you have any insight into the issue my colleague described above?

**Comment by jelling** [comment]
Could the issue here be literally what the error message says?

Error:

```
2022-07-15T19:08:48.9661171Z ⚠  Function 'createPortalLink is missing a trigger in extension.yaml. Please add one, as triggers defined in code are ignored. {"metadata":{"emulator":{"name":"functions"},"message":"Function 'createPortalLink is missing a trigger in extension.yaml. Please add one, as triggers defined in code are ignored."}}
2022-07-15T19:08:48.9663518Z ⚠  Function 'handleWebhookEvents is missing a trigger in extension.yaml. Please add one, as triggers defined in code are ignored. {"metadata":{"emulator":{"name":"functions"},"message":"Function 'handleWebhookEvents is missing a trigger in extension.yaml. Please add one, as triggers defined in code are ignored."}}
```

And those functions don't have a trigger:

```
  - name: createPortalLink
    type: firebaseextensions.v1beta.function
    description: >-
      Creates links to the customer portal for the user to manage their payment & subscription details.
    properties:
      location: ${LOCATION}
      runtime: nodejs14
      httpsTrigger: {}

  - name: handleWebhookEvents
    type: firebaseextensions.v1beta.function
    description: >-
      Handles Stripe webhook events to keep subscription statuses in sync and update custom claims.
    properties:
      location: ${LOCATION}
      runtime: nodejs14
      httpsTrigger: {}
  ```
