### ISSUE TITLE
Should we move the prices subcollection into the original product document? 

### ISSUE THREAD

**Issue by ToddKerpelman** [stripe/stripe-firebase-extensions#79]
# Feature request

- Extension name: `firestore-stripe-subscriptions`
 
Hi, Stripe Engineers! So I noticed that when we create a new subscription product with a set of pricing options in Stripe, those pricing options get added to a "prices" subcollection for the individual product. While that seems logical, it means that when you want to get a list of products and their prices, you have to query both the products collection, and then go back and query every individual prices subcollection for every product. This leads to longer load times, more complex code, and more reads charged to the developer.

So I'm wondering if it would make sense to take all of those pricing documents and simply merge them into the original product document, probably as a map field. It might look something like this:

```
prod_abcdefg:
   active: true
   description: "Foo"
   images: ["http://..."]
   name: "Bar"
   prices: {
    price_123: {active: true, currency: "usd", description: "...", interval: "month", // etc.}
    price_456: {active: true, currency: "usd", description: "...", interval: "week", // etc.}
    price_789: {active: true, currency: "usd", description: "...", interval: "year", // etc.}
   }
   role: "Premium"
```

This would mean that as a developer, you can much more easily query for a list of products and all of their prices with a single database call.

The potential drawbacks to this approach are that a) There would be no server-side filtering of prices. (That is, a client would retrieve all pricing options, and if there were inactive ones or other pricing options you wanted to keep hidden from the client, that wouldn't be possible), b) You would always retrieve all pricing options even if you didn't need or want them. (Maybe there are situations where you only want to display products and not show pricing information, so we'd be downloading some unnecessary info), c) If you had _a lot_ of pricing options, you could run up against the 1mb / document limit (but that would be pretty unusual), and d) It's a non-backwards-compatible change.

Since I don't have enough familiarly with the Stripe user base or their typical workflows, I don't know if any of these drawbacks are legitimate concerns, but I just thought I should bring this idea up in case you hadn't considered it.
